
global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: prometheus
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets:
          - localhost:9090
  - job_name: livepeer-node
    scrape_interval: 5s
    static_configs:
      - targets:
          - orchestrator:7935
        labels:
          livepeer_node_type: orchestrator
      - targets:
          - broadcaster:7936
        labels:
          livepeer_node_type: broadcaster
  - job_name: cadvisor
    scrape_interval: 5s
    dns_sd_configs:
      - names:
          - tasks.cadvisor
        type: A
        port: 8080
  - job_name: node-exporter
    scrape_interval: 5s
    dns_sd_configs:
      - names:
          - tasks.node-exporter
        type: A
        port: 9100
